[package]
name = "twrit-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "twrit"
path = "src/main.rs"

[dependencies]
#= Tomet
tomet-ast = { workspace = true }
tomet-load = { workspace = true }
tomet-parser = { workspace = true }
tomet-semantics = { workspace = true }
tomet-tree = { workspace = true }

#= Crates.io
anyhow = { workspace = true }
cargo_metadata = { workspace = true }
clap = { workspace = true }
ignore = { workspace = true }
